### ISSUE TITLE
Lambda Error and No Splunk Data

### ISSUE THREAD

**Issue by dcahill** [amiracle/grand_central#10]
Can't find a solution in the documentation. We also got a working registered ACM cert as letsencrypt we suspected had problems. Current error in kinesis is:

The Lambda function was successfully invoked but it returned an error result.

Do you have any documentation or assistance that might help fix this please?

**Comment by dcahill** [comment]
Seeing the following error in lambda:

'source': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 182, in handler
    records = list(processRecords(event['records']))
  File "/var/task/lambda_function.py", line 78, in processRecords
    st = data['source'].replace(".", ":") + ":firehose"
KeyError: 'source'

Would also be good to have the option in kinesis to enable cloudwatch error logging in the deploy template maybe?

But bigger problem is there any solution to this current lambda error?

**Comment by nstonesplunk** [comment]
@dcahill do you know which data sources (specifically the CloudWatch Events) were selected before deployment?

**Comment by dcahill** [comment]
I have tried a deployment using only CloudTrail. The other one has many many CloudWatch events selected but neither are working.

I know this might be slightly unorthodox, but I'm supposed to demo this product to some high level folks at my agency. Is there any chance I could email you from my government email or even call to collaborate on this briefly? I'm wanting to use your code as the center point for our splunk deployment solution.

**Comment by dcahill** [comment]
Ok oddly out of nowhere Kinesis decided to start sending some amount of cloudtrail data to the HEC... No idea why it just started now but we'll keep an eye on this.

Hoping in the future for some more extensive documentation regarding kinesis and grandcentral as it relates to EACH log service. Thanks!
