### ISSUE TITLE
grand_central.spl is missing from the repo

### ISSUE THREAD

**Issue by rawanbadawi** [amiracle/grand_central#15]
Hi I cannot find the spl file to upgrade to the latest grandcentral app

grand_central /
You’ve activated the file finder. Start typing to filter the file list. Use ↑ and ↓ to navigate, enter to view files, esc to exit.
 .gitignore
 Grand_Central_Deployer.json
 LICENSE
 README.md
 README/cloudformation_templates.conf.spec
 README/ensemble_aws_accounts.conf.spec
 README/grand_central_aws_accounts.conf.spec
 README/splunk_accounts.conf.spec
 app.manifest
 appserver/static/pages/ensemble_accounts.js
 appserver/static/pages/grand_central_accounts.js
 appserver/static/pages/templates.js
 appserver/static/pages/trumpet.js
 appserver/templates/layout.html
 appserver/templates/templates.html
 appserver/templates/trumpet.html
 bin/Archive.zip
 bin/README
 bin/aws_cloudwatch_pricelist.sh
 bin/aws_ec2_pricelist.sh
 bin/aws_kinesis_firehose_pricelist.sh
 bin/aws_kinesis_pricelist.sh
 bin/aws_lambda_pricelist.sh
 bin/aws_s3_pricelist.sh
 bin/base_eai_handler.py
 bin/bin/jp.py
 bin/bin/rst2html.py
 bin/bin/rst2html4.py
 bin/bin/rst2html5.py
 bin/bin/rst2latex.py
 bin/bin/rst2man.py
 bin/bin/rst2odt.py
 bin/bin/rst2odt_prepstyles.py
 bin/bin/rst2pseudoxml.py
 bin/bin/rst2s5.py
 bin/bin/rst2xetex.py
 bin/bin/rst2xml.py
 bin/bin/rstpep2html.py
 bin/boto3/__init__.py
 bin/boto3/compat.py
 bin/boto3/data/cloudformation/2010-05-15/resources-1.json
 bin/boto3/data/cloudwatch/2010-08-01/resources-1.json
 bin/boto3/data/dynamodb/2012-08-10/resources-1.json
 bin/boto3/data/ec2/2014-10-01/resources-1.json
 bin/boto3/data/ec2/2015-03-01/resources-1.json
 bin/boto3/data/ec2/2015-04-15/resources-1.json
 bin/boto3/data/ec2/2015-10-01/resources-1.json
 bin/boto3/data/ec2/2016-04-01/resources-1.json
 bin/boto3/data/ec2/2016-09-15/resources-1.json
 bin/boto3/data/ec2/2016-11-15/resources-1.json

Can you please commit it or update installation instructions?

Thanks

**Comment by amiracle** [comment]
I removed it since it was causing issues when I packaged up the app on my local instance. Here is the link to the SPL file : https://grandcentraldeployment.s3.amazonaws.com/grand_central.spl
