### ISSUE TITLE
'ap-southeast-2' region missing from list of regions when deploying data collection

### ISSUE THREAD

**Issue by nvonkorff** [amiracle/grand_central#4]
The 'ap-southeast-2' region seems to be missing when I click Deploy Data Collection on a configured account and the "Apply an AWS CloudFormation template" screen launches. I am also not able to enter it manually, only select from what is available.

Could you please include 'ap-southeast-2' in the list of available regions?

**Comment by amiracle** [comment]
Version 1.1.1 fixes this issue.

**Comment by nvonkorff** [comment]
Thanks for looking at this. I still seem to be facing this issue in V1.1.1:
![grand_central_apsoutheast2_missing](https://user-images.githubusercontent.com/37675861/74001762-e43d6a00-49c0-11ea-8a8a-985be29a61dc.png)

No "ap-southeast-2" under Asia-Pacific.

**Comment by nstonesplunk** [comment]
Could you try to bump the cache by hitting this url {host:port}/en-US/_bump and clicking "Bump Version"?

**Comment by nvonkorff** [comment]
Thanks @nstonesplunk, that fixed it. I thought restarting the Splunk instance would have done the trick, but once I bumped the cache, ap-southeast-2 appeared. Thanks again.
