### ISSUE TITLE
Still seeing stack creation failure for Config Lambdas

### ISSUE THREAD

**Issue by stevebidondo** [amiracle/grand_central#6]
Updated to version 1.1.1

The following resource(s) failed to create: [ConfigurationRecorderSanitiser, ConfigNotificationEventRule]: ConfigurationRecorderSanitiser

The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: c09f9002-ae45-426e-a47c-2e796e0313b0)

Update of runtime variables for node here? https://github.com/amiracle/grand_central/blob/1b82f7917a68493670b9e65a043531d2ecc2dff6/bin/botocore/data/lambda/2015-03-31/service-2.json

**Comment by stevebidondo** [comment]
investigating

**Comment by nstonesplunk** [comment]
Could you try to bump the cache by hitting this url {host:port}/en-US/_bump and clicking "Bump Version"? Will also try to replicate.

**Comment by stevebidondo** [comment]
the bump seemed to have worked, getting past that lambda failure, thanks.  Now seeing:

ConfigBucketConfiguration | CREATE_FAILED | Failed to create resource. See the details in CloudWatch Log Stream: 2020/01/30/[$LATEST]343f1fdf8d1a4d75af6fda794e42c780
log stream details below...

2020-01-30T11:24:24.165-08:00 | START RequestId: 05cc118d-447e-407d-93b5-f8d304e5cf60 Version: $LATEST
-- | --
2020-01-30T11:24:25.025-08:00 | END RequestId: 05cc118d-447e-407d-93b5-f8d304e5cf60
2020-01-30T11:24:25.025-08:00 | REPORT RequestId: 05cc118d-447e-407d-93b5-f8d304e5cf60 Duration: 859.94 ms Billed Duration: 900 ms Memory Size: 128 MB Max Memory Used: 90 MB Init Duration: 356.43 ms
2020-01-30T11:24:59.177-08:00 | START RequestId: dc41f451-81d1-4684-942f-3496b4622e9c Version: $LATEST
2020-01-30T11:24:59.657-08:00 | END RequestId: dc41f451-81d1-4684-942f-3496b4622e9c
2020-01-30T11:24:59.657-08:00 | REPORT RequestId: dc41f451-81d1-4684-942f-3496b4622e9c Duration: 478.42 ms Billed Duration: 500 ms Memory Size: 128 MB Max Memory Used: 91 MB

**Comment by nstonesplunk** [comment]
Is the AWS Config service turned on in the account? If so is there an existing bucket it is writing to?

**Comment by stevebidondo** [comment]
Yup, Config recording is turned on and currently delivering to the following:

S3 bucket name
aws-controltower-logs-649566760083-us-west-2
SNS topic name
AllConfigNotifications

Would it be better to send these as CWE since this delivery method is existing?

**Comment by nstonesplunk** [comment]
The CWE events are only config change notifications so may not include everything you are looking for.

The config snapshot option will send over the scheduled snapshot stored in s3, but does not include change notifications.

I'm not yet sure why you are getting a failure - there does not seem to be any obvious error messaging. The failing lambda should be checking for existing Config delivery channels and recorders and picking up the existing configured s3 bucket before moving on with the rest of the template. 

I'm also not sure why nothing is getting logged. Need to investigate further and try to replicate

**Comment by sbidondo** [comment]
More than happy to hop on Webex if you want to explore our stack.  Let me know.

**Comment by stevebidondo** [comment]
ok, artifact of failed deployments from another stack.  all good now.

**Comment by nstonesplunk** [comment]
Do you remember the solution to this issue? Was it specifically deleting previously failed/hung stacks from Grand Central? Or other unrelated stacks/something else. Trying to reproduce the issue for a troubleshooting guide and so far unable to.
