### ISSUE TITLE
Broad Permissions

### ISSUE THREAD

**Issue by bonnern** [amiracle/grand_central#7]
Good day,

The permissions policy seems quite broad for this to function.  For instance s3:DeleteBucket for Resource": "*" does not seem necessary.  Have the permissions been scoped to least privilege for the integration to function?

This method for gathering AWS data for Splunk looks very promising but the scope of the permissions make me a bit uneasy.

Thanks

**Comment by amiracle** [comment]
I will be working with the team to make these permissions more specific to the resources that Grand Central uses.

**Comment by irvine-j** [comment]
It's that  `"Resource": "*"` that's the killer.  I'm reasonably fine with things controlling their own assets as long as those are reasonably constrained, but when you give carte blanche for some of these, it gets thoroughly dangerous.  There's quite a bit here that can be an issue for exfiltration of data or security configuration, but that's the nature of any reporting platform.  

Off-hand, the particularly problematic ones on scope are:

- cloudwatch:PutMetricData
- config:DeliverConfigSnapshot
- events:PutEvents
- events:PutRule
- events:PutTargets
- firehose:DeleteDeliveryStream
- iam:AttachRolePolicy
- iam:CreateRole
- iam:CreateUser
- iam:DeleteRole
- iam:DeleteRolePolicy
- iam:DeleteUser
- iam:DetachRolePolicy
- iam:PassRole
- iam:PutRolePolicy
- kms:Decrypt
- lambda:DeleteFunction
- lambda:RemovePermission
- logs:DeleteSubscriptionFilter
- logs:PutSubscriptionFilter
- s3:DeleteBucket
- s3:GetObject
- s3:PutBucketVersioning
- sns:Publish
- sqs:DeleteMessage
- sqs:ReceiveMessage
- sqs:SendMessage
- sts:AssumeRole

s3:GetObject is a bit different here than the rest, but since it gives that user the ability to literally see anything that's been put in an S3 bucket in the account, I thought it was worth calling out in the list.

**Comment by amiracle** [comment]
I just went in and fix the permissions so that the resource "*" is now just limited to less impactful services. Here is a copy of the new policy:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "config:GetComplianceSummaryByConfigRule",
                "iam:GetAccountPasswordPolicy",
                "cloudformation:ListExports",
                "logs:DeleteSubscriptionFilter",
                "cloudwatch:PutMetricData",
                "ec2:DescribeInstances",
                "kms:Decrypt",
                "kinesis:Get*",
                "lambda:GetFunctionConfiguration",
                "ec2:DescribeSnapshots",
                "sns:ListEndpointsByPlatformApplication",
                "kinesis:ListStreams",
                "cloudwatch:DescribeAlarmsForMetric",
                "cloudwatch:ListDashboards",
                "ec2:DescribeVolumes",
                "logs:GetLogEvents",
                "events:RemoveTargets",
                "lambda:DeleteFunction",
                "ec2:DescribeReservedInstances",
                "ec2:DescribeKeyPairs",
                "cloudformation:CreateStackSet",
                "ec2:DescribeNetworkAcls",
                "events:PutEvents",
                "cloudwatch:DescribeInsightRules",
                "events:DescribeRule",
                "sns:GetPlatformApplicationAttributes",
                "sns:GetSubscriptionAttributes",
                "cloudwatch:GetMetricStatistics",
                "sns:ListPhoneNumbersOptedOut",
                "sns:GetEndpointAttributes",
                "sts:AssumeRole",
                "logs:PutSubscriptionFilter",
                "ec2:DescribeSubnets",
                "sns:GetSMSAttributes",
                "cloudformation:ValidateTemplate",
                "cloudformation:CreateUploadBucket",
                "cloudformation:DescribeStackDriftDetectionStatus",
                "autoscaling:Describe*",
                "ec2:DescribeAddresses",
                "cloudwatch:GetMetricData",
                "logs:DescribeLogStreams",
                "events:PutRule",
                "ec2:DescribeRegions",
                "sns:ListTopics",
                "cloudwatch:ListMetrics",
                "cloudwatch:DescribeAnomalyDetectors",
                "cloudformation:EstimateTemplateCost",
                "cloudformation:DescribeAccountLimits",
                "cloudwatch:GetMetricWidgetImage",
                "config:DeliverConfigSnapshot",
                "sqs:ListQueues",
                "cloudformation:ListStacks",
                "logs:DescribeLogGroups",
                "cloudformation:ListImports",
                "kinesis:DescribeStream",
                "sns:ListSubscriptions",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeImages",
                "events:DeleteRule",
                "events:PutTargets",
                "s3:ListAllMyBuckets",
                "ec2:DescribeVpcs",
                "iam:ListUsers",
                "lambda:RemovePermission",
                "sns:ListPlatformApplications"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "sqs:DeleteMessage",
                "s3:GetLifecycleConfiguration",
                "s3:GetBucketTagging",
                "s3:GetBucketLogging",
                "sqs:ReceiveMessage",
                "s3:CreateBucket",
                "iam:CreateRole",
                "s3:ListBucket",
                "s3:GetAccelerateConfiguration",
                "iam:AttachRolePolicy",
                "iam:PutRolePolicy",
                "iam:CreateUser",
                "s3:GetBucketPolicy",
                "s3:GetObjectAcl",
                "firehose:DeleteDeliveryStream",
                "iam:PassRole",
                "config:GetComplianceDetailsByConfigRule",
                "iam:DetachRolePolicy",
                "sns:Publish",
                "iam:DeleteRolePolicy",
                "config:DescribeConfigRules",
                "s3:DeleteBucket",
                "s3:PutBucketVersioning",
                "iam:ListAccessKeys",
                "s3:GetBucketPolicyStatus",
                "s3:GetBucketPublicAccessBlock",
                "iam:GetRole",
                "sqs:GetQueueUrl",
                "config:DescribeConfigRuleEvaluationStatus",
                "firehose:CreateDeliveryStream",
                "iam:GetAccessKeyLastUsed",
                "sqs:SendMessage",
                "iam:DeleteRole",
                "sqs:GetQueueAttributes",
                "iam:DeleteUser",
                "firehose:DescribeDeliveryStream",
                "s3:GetObject",
                "s3:GetBucketCORS",
                "iam:GetUser",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::grandcentral*",
                "arn:aws:s3:::*/*",
                "arn:aws:config:*:*:config-rule/grandcentral*",
                "arn:aws:firehose:*:002404001714:deliverystream/grandcentral*",
                "arn:aws:sqs:*:*:grandcentral*",
                "arn:aws:iam::*:role/grandcentral*",
                "arn:aws:iam::*:user/grandcentral*",
                "arn:aws:sns:*:*:grandcentral*"
            ]
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "sns:Get*",
                "sns:List*"
            ],
            "Resource": "arn:aws:sns:*:*:grandcentral*"
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": [
                "cloudwatch:List*",
                "cloudwatch:Get*",
                "cloudwatch:Describe*"
            ],
            "Resource": [
                "arn:aws:cloudwatch::*:dashboard/*",
                "arn:aws:cloudwatch:*:*:insight-rule/*",
                "arn:aws:cloudwatch:*:*:alarm:*"
            ]
        },
        {
            "Sid": "VisualEditor4",
            "Effect": "Allow",
            "Action": "cloudformation:*",
            "Resource": [
                "arn:aws:cloudformation:*:*:stack/grandcentral*/*",
                "arn:aws:cloudformation:*:*:stackset/*:grandcentral*"
            ]
        }
    ]
}
`

**Comment by amiracle** [comment]
Closing the issue, if there are any additional issues with this policy, please open a new issue and we will look into it.
