### ISSUE TITLE
Deploying changes to existing CloudFormation stacks produces a region error

### ISSUE THREAD

**Issue by nvonkorff** [amiracle/grand_central#9]
Steps to reproduce:
- Deploy data collection stack
- Update data collection stack
<img width="874" alt="Screen Shot 2020-02-19 at 2 33 02 pm" src="https://user-images.githubusercontent.com/37675861/74806106-2e1b3e00-5339-11ea-9e0a-20640c9ad178.png">

**Comment by amiracle** [comment]
Test : Setup Config and CloudTrail in ap-southeast-1, ap-southeast-2. Also tested removal of settings and it worked as well. 

Config : Test Completed Successfully for both regions:
![Screen Shot 2020-02-19 at 11 53 42 AM](https://user-images.githubusercontent.com/786468/74855457-bb956880-530e-11ea-8da1-fc4f403376b0.png)

CloudTrail : Test Completed Successfully for both regions:
![Screen Shot 2020-02-19 at 11 58 14 AM](https://user-images.githubusercontent.com/786468/74855846-365e8380-530f-11ea-8525-20d11685ccd4.png)

Please validate that the permission for the IAM user you are using is set properly. Also, can you paste either the events or resources for the CloudFormation template.  

Test platform : Mac OSX 10.14.6 / Splunk 8.0.1 / Grand Central 1.1.1

**Comment by amiracle** [comment]
I am unable to reproduce the error. Please re-open the case and post any error messages you see so that we can troubleshoot this more if necessary.
